### ISSUE TITLE
Error with negative numbers recognition 

### ISSUE THREAD

**Issue by Il-Basta-Paolo** [Guglio95/vonsimulator#5]
Hi, 
while i was testing a code i wrote I noticed that loading, multiplying and dividing with a negative number by using "=" operator the program doesn't recognise negative numbers, for example:
`LOAD=  5
MULT= -1
WRITE
END`  
prints the number 5.
(I also noticed that negative numbers recognition works with the "READ" command or when the negative number is the result of an algebric operation).
Regards, Paolo.

**Comment by aguglie** [comment]
Hi Paolo,
Thanks for pointing that out! Would you be open to submitting a PR with the fix? 
Andrea

**Comment by Il-Basta-Paolo** [comment]
Yes, I did the PR, don't know if I did it in the right way, this is the first time I do something like this. However I tested the corrected code and it works, so I hope that helped.

Il 8 set 2024 12:38, Andrea G ***@***.***> ha scritto:

Hi Paolo,
Thanks for pointing that out! Would you be open to submitting a PR with the fix?
Andrea
